### ISSUE TITLE
Integrating this with the users table

### ISSUE THREAD

**Issue by Halnex** [mohankumaranna/comment#1]
Any change you make this work with users table?

**Comment by mohankumaranna** [comment]
no, i didn't make change on user table.

**Comment by Halnex** [comment]
I see that. but can you?

Can you change your code so it will work with the users table and "user_id"

I'd rather if you did it.

**Comment by mohankumaranna** [comment]
you can customize it yourself to fit your needs.

Date: Wed, 14 Oct 2015 06:42:53 -0700

**Comment by Halnex** [comment]
All I have to do is replace $comment->email and $comment->name with `Auth::id()`  on the post-on-comment() method, correct?

Is there anything else?

PS: if you're interested in contributing in a bigger project, I'd like to invite you to this https://github.com/Halnex/laravel-reddit

It's a reddit clone written in laravel, it's almost done, I'm just still hanging on the threaded-comments.

Please feel free to make a commit. Would love that.

**Comment by mohankumaranna** [comment]
Yes.  In the CommentController, email and name can be removed.  Add 'id' to save it into 'user_id' field of Comment table.  I guess that should do.

Date: Wed, 14 Oct 2015 07:06:47 -0700

**Comment by Halnex** [comment]
Hello again, I have a problem integrating it into my own app. I would like to show the comment box on my posts so I included leave_a_comment.blade.php into my post view but I keep getting this error

> Method [view_data] does not exist.

I already have a PostsController and its views, why can I integrate it with your CommentController? do I have to pass all these variables from my PostsController too?

**Comment by mohankumaranna** [comment]
View part was included for illustration purpose.  Please refer below code sample for integrating with a home page.  I hope, this may be of some help.

<?php

namespace App\Http\Controllers;

use Eastgate\Comment\CommentController;
use Illuminate\Http\Request;

class HomeController extends Controller {
	
	public function home(Request $request){
		$view_data = CommentController::view_data($request);
		return view('pages.home_page', $view_data);
	}
}

**Comment by Halnex** [comment]
I have managed to partially integrate it with my app, however, when I try to submit a root comment, I get an sql error 

> SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'comment' cannot be null (SQL: insert into `comments` (`user_id`, `comment`, `parent_id`, `parents`, `updated_at`, `created_at`) values (1, , , 0, 2015-10-17 15:12:30, 2015-10-17 15:12:30))

the jQuery doesn't seem to be passing any data to the controller.

I have tried many methods to loop through the `comment-fields` div but none of them worked.

Please refer to this stackoverflow.com question: http://stackoverflow.com/questions/33181666/jquery-loop-through-comment-div-and-get-fields-values

I believe my problem is here in `comment.js`

    var formData = new FormData();
    var arrayelem = commenter_fields();
    var elem;
    for(var i=0, size = arrayelem.length; i<size; i++){
        elem = arrayelem[i];
        formData.append(elem, $('#'+elem).val());
    }
    formData.append('per_page', $('.comments_per_page').val());

**Comment by Halnex** [comment]
Can you please tell me why I can't retrieve the `post_id` of hidden field in `comment_list()` method?

    protected function comment_list($per_page, Request $request){
        $postId = Input::get('commenter_post');
        dd($postId); // returns null
        $root_comments = Comment::root_comments($postId);

But the same variable return the post_id value in `post_this_comment()` method

**Comment by Halnex** [comment]
I am trying to show comments of current `post_id` - I have tried doing this

    public static function root_comments($postId){
        return self::child_comments(0, 'desc')->where('post_id', $postId);
    }

But I can't retrieve the `post_id` of hidden field in `comment_list()` method

    protected function comment_list($per_page, Request $request){
        $postId = Input::get('commenter_post');
        dd($postId); // returns null
        $root_comments = Comment::root_comments($postId);

Can you please tell me how to achieve this?

**Comment by Halnex** [comment]
Ok, so I've managed to integrate it into my own app. At the moment, I am trying to show comments of current post that I am viewing. So I did this to `Comment` Model

    public static function root_comments($postId) {
        return self::child_comments(0, 'desc')->where('post_id', $postId);
    }

And in `CommentController` I did this

    protected function comment_list($per_page, Request $request, Post $post) {
		$postId = $post->id;
		$root_comments = Comment::root_comments($postId);
		$root_with_replies = $this->include_replies_for($root_comments);
		$paginated_comments = $this->paginate($root_with_replies, $per_page, $request);
		return $paginated_comments;
	}

And I added `$post` to all other methods as well such as this

	public static function view_data(Request $request, Post $post) { // Post $post
		$instance = new Self;
		$per_page = session('per_page')?session('per_page'):config('constants.per_page'); // default per page on opening the comment page
		$result['per_page'] = $per_page;
		$result['comments'] = $instance->comment_list($per_page, $request, $post); // $post
		$result['total_comments'] = $instance->total_comments();
		$result['captcha_builder'] = $instance->captcha_builder();
		return $result;
	}

 However, when I submit a new comment, it redirects me to an empty `comment_list` , I have to refresh the page manually to be able to see the comments.

Any thoughts?
